### ISSUE TITLE
"This certificate or one of the certificates in the certificate chain is not up to date"

### ISSUE THREAD

**Issue by wgreenihrcorp** [dennyzhang/cheatsheet.dennyzhang.com#3]
I got this displayed when I attempted to access https://cheatsheet.dennyzhang.com/#

Screenshot attached
![CheetsheetDennyZhangCertificateIssue](https://user-images.githubusercontent.com/43206183/141307932-a257dd1b-8653-44fd-90f6-03e694226f9f.png)

![image](https://user-images.githubusercontent.com/43206183/141307700-79d1d17e-5e0e-46e8-803e-09e2c8b5789d.png)

**Comment by dennyzhang** [comment]
thanks for reporting. Should be back now.
